KS-2-2 Arithmetic lesson 2 fixed
rmnshkv/Kotlin-training.-Sprint pull request #7
Opened 2023-09-15 08:50 UTC by rmnshkv

2023-09-15 16:49 UTC, ievetrov requested changes

2023-09-15 16:49 UTC, ievetrov commented on src/main/kotlin/lesson2.kt
> +    val all_staff_salary = 1500000
Согласно конвенции стиля Котлин обычные переменные называем строго в CamelCase)

2023-09-15 16:49 UTC, ievetrov commented on src/main/kotlin/lesson2.kt
> +    val all_staff_salary = 1500000
и оперируем только переменными, которые объявили ранее. никаких взятых из головы "голых" значений) все высчитываем в коде

2023-09-17 00:01 UTC, danelyan requested changes
...

2023-09-17 00:02 UTC, ievetrov requested changes
Уже намного лучше!

Только давай переменные с маленькой буквы писать. Все таки глазу привычнее (и в конвенции прописано), что с большой буквы мы пишем классы. Переменные можно с большой, если это экземпляр object:

https://kotlinlang.org/docs/coding-conventions.html#property-names

2023-09-21 09:14 UTC, ievetrov approved these changes
все круто) давай только поднажмем!)

2023-09-26 11:02 UTC, closed without merging